
cc_test(
    name = "test",
    srcs = ["test.cpp"],
    visibility = ["//visibility:public"],
    deps = [
      "//qir/cc/qir-module:qir-module",
      "//qir/rust/logger:logger",      
    ],
    args = [],
)
