


py_binary(
    name = "example",
    srcs =["example.py"],
    main = "example.py",
    deps = [
        "//qir/cc/pyllvm:pyllvm",
    ],
    data = [ ],
    args = [ ],
    visibility = [
        "//visibility:public",
    ],
)