cc_library(
    name = "qir-module",
    srcs = glob(["*.cpp"]),
    hdrs = glob(["*.hpp"]),    
    visibility = ["//visibility:public"],
    deps = [
      "//qir/cc/llvm:lib",
      "//qir/rust/logger:logger",
    ],
)
