
cc_test(
    name = "test",
    srcs = ["test.cpp"],
    visibility = ["//visibility:public"],
    deps = [
      "//svadilfari/cc/script-builder:script-builder",
      "//svadilfari/rust/logger:logger",      
    ],
    args = [],
)
